name: graph
channels:
  - pyg
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - cudatoolkit=10.2
  - numpy
  - pyg
  - python
  - pip
  - pytorch=1.11.0=py3.9_cuda10.2_cudnn7.6.5_0
  - pytorch-cluster
  - pytorch-scatter
  - pytorch-sparse
  - pytorch-spline-conv
  - scikit-learn
  - scipy
  - torchvision
  - tqdm
  - ipykernel
  - xarray
  - zarr
  - dask
  - matplotlib
  - seaborn
  - netCDF4
  - pip:
      - datasets
      - einops
      - fsspec==2022.2.0
      - h3==3.7.3
      - huggingface-hub
      - pandas
      - pyarrow
      - responses
      - torch-geometric-temporal
      - pysolar
      - pytorch-lightning
      - deepspeed
      - click
